//Locates search button on homepage
const searchbtn = document.getElementById("searchbtn");
//Locates all results loaded on page and makes a collection
const result = document.getElementsByClassName("result");


//changes result color on hover
function resultOnHover(result){
    result.target.style.backgroundColor= "#be4f0c";
    result.target.style.borderColor="#be4f0c";

}

//restores result background color on HoverOut
function resultOnHoverOut(result){
    result.target.style.backgroundColor= "#F54927";
    result.target.style.borderColor= "#F54927";
}

//Addes event listeners to detect when user's mouse enters or leaves a result box
function hoverHandlingResults(result){
    result.addEventListener("mouseenter", resultOnHover);
    result.addEventListener("mouseleave", resultOnHoverOut);
}

//iterates through HTMLCollectiong generated by const result
//then adds a smoothing css color transtion and finally adds the event listeners to the DOM Element
for (i=0;i<=result.length;i++){
    const element = result[i];
    element.classList.add("result-transition");
    hoverHandlingResults(element);

}


//debug purposes
console.log("We made it we found the End!")
